-- MySQL Script generated by MySQL Workbench
-- 11/10/15 10:08:37
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema divsec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `divsec` DEFAULT CHARACTER SET utf8 ;
USE `divsec` ;

-- -----------------------------------------------------
-- Table `divsec`.`division`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`division` (
  `div_id` INT(11) NOT NULL AUTO_INCREMENT,
  `div_name` VARCHAR(50) NULL DEFAULT NULL,
  `div_active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`div_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`notification` (
  `ntn_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ntn_type` VARCHAR(100) NULL DEFAULT NULL,
  `ntn_active` BINARY(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ntn_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`public_individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`public_individual` (
  `pi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pi_name` VARCHAR(100) NULL DEFAULT NULL,
  `pi_address1` VARCHAR(50) NULL DEFAULT NULL,
  `pi_address2` VARCHAR(50) NULL DEFAULT NULL,
  `pi_address3` VARCHAR(50) NULL DEFAULT NULL,
  `pi_land_phone` VARCHAR(10) NULL DEFAULT NULL,
  `pi_mobile_phone` VARCHAR(10) NULL DEFAULT NULL,
  `pi_email` VARCHAR(100) NULL DEFAULT NULL,
  `pi_ind_user_id` INT(11) NULL DEFAULT NULL,
  `pi_user_pwd` VARCHAR(100) NULL DEFAULT NULL,
  `pi_nic` VARCHAR(10) NULL DEFAULT NULL,
  `pi_dob` DATETIME NULL DEFAULT NULL,
  `pi_gender` VARCHAR(5) NULL DEFAULT NULL,
  `pi_note` VARCHAR(100) NULL DEFAULT NULL,
  `pi_user_id` INT(11) NULL DEFAULT NULL,
  `pi_notfication_type_id` INT(11) NULL DEFAULT NULL,
  `pi_active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`pi_id`),
  UNIQUE INDEX `pi_user_id_UNIQUE` (`pi_ind_user_id` ASC),
  INDEX `pi_notfication_id_idx` (`pi_notfication_type_id` ASC),
  CONSTRAINT `fk_pi_notfication_type_id`
    FOREIGN KEY (`pi_notfication_type_id`)
    REFERENCES `divsec`.`notification` (`ntn_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`subject` (
  `sbj_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sbj_name` VARCHAR(50) NULL DEFAULT NULL,
  `sbj_active` BIT(1) NULL DEFAULT NULL,
  `sbj_div_id` INT(11) NULL DEFAULT NULL,
  `duration` INT(11) NULL DEFAULT NULL,
  `cost` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`sbj_id`),
  INDEX `fk_sbj_div_id_idx` (`sbj_div_id` ASC),
  CONSTRAINT `fk_sbj_div_id`
    FOREIGN KEY (`sbj_div_id`)
    REFERENCES `divsec`.`division` (`div_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`user_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`user_category` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(50) NULL DEFAULT NULL,
  UNIQUE INDEX `cat_name_UNIQUE` (`cat_name` ASC),
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COMMENT = 'categories are saved. Admin, Head of Divison, Staff and publ';


-- -----------------------------------------------------
-- Table `divsec`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`staff` (
  `stf_id` INT(11) NOT NULL AUTO_INCREMENT,
  `stf_name` VARCHAR(50) NULL DEFAULT NULL,
  `stf_category_id` INT(11) NOT NULL DEFAULT NULL,
  `stf_user_id` VARCHAR(10) NULL DEFAULT NULL,
  `stf_password` VARCHAR(100) NULL DEFAULT NULL,
  `stf_dvision_id` INT(11) NOT NULL,
  `stf_email` VARCHAR(100) NULL DEFAULT NULL,
  `stf_mobile` VARCHAR(10) NULL DEFAULT NULL,
  `stf_note` VARCHAR(100) NULL DEFAULT NULL,
  `stf_active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`stf_id`),
  UNIQUE INDEX `stf_user_id_UNIQUE` (`stf_user_id` ASC),
  INDEX `fk_stf_divsion_id_idx` (`stf_dvision_id` ASC),
  INDEX `fk_stf_cat_id_idx` (`stf_category_id` ASC),
  CONSTRAINT `fk_stf_divsion_id`
    FOREIGN KEY (`stf_dvision_id`)
    REFERENCES `divsec`.`division` (`div_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stf_cat_id`
    FOREIGN KEY (`stf_category_id`)
    REFERENCES `divsec`.`user_category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`request` (
  `req_id` INT(11) NOT NULL AUTO_INCREMENT,
  `req_subject_id` INT(11) NULL DEFAULT NULL,
  `req_division_id` INT(11) NULL DEFAULT NULL,
  `req_public_id` INT(11) NULL DEFAULT NULL,
  `req_ent_date` DATETIME NULL DEFAULT NULL,
  `req_note` VARCHAR(100) NULL DEFAULT NULL,
  `req_fees` DECIMAL(10,2) NULL DEFAULT NULL,
  `req_to_be_approved` BIT(1) NULL DEFAULT NULL,
  `req_user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`req_id`),
  INDEX `fk_req_public_id_idx` (`req_public_id` ASC),
  INDEX `fk_req_division_id_idx` (`req_division_id` ASC),
  INDEX `fk_req_user_id_idx` (`req_user_id` ASC),
  INDEX `fk_req_subject_id_idx` (`req_subject_id` ASC),
  CONSTRAINT `fk_req_division_id`
    FOREIGN KEY (`req_division_id`)
    REFERENCES `divsec`.`division` (`div_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_public_id`
    FOREIGN KEY (`req_public_id`)
    REFERENCES `divsec`.`public_individual` (`pi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_subject_id`
    FOREIGN KEY (`req_subject_id`)
    REFERENCES `divsec`.`subject` (`sbj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_user_id`
    FOREIGN KEY (`req_user_id`)
    REFERENCES `divsec`.`staff` (`stf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'details about the request submitted by the public individual';


-- -----------------------------------------------------
-- Table `divsec`.`aproval`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`aproval` (
  `app_id` INT(11) NOT NULL AUTO_INCREMENT,
  `app_request_id` INT(11) NOT NULL,
  `app_is_approved` BIT(1) NULL DEFAULT NULL,
  `app_date` DATETIME NULL DEFAULT NULL,
  `app_ent_date` DATETIME NULL DEFAULT NULL,
  `app_user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`app_id`),
  INDEX `fk_app_request_id_idx` (`app_request_id` ASC),
  CONSTRAINT `fk_app_request_id`
    FOREIGN KEY (`app_request_id`)
    REFERENCES `divsec`.`request` (`req_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`email_setup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`email_setup` (
  `email_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email_is_out_look` BINARY(1) NULL DEFAULT NULL,
  `email_sender_name` VARCHAR(100) NULL DEFAULT NULL,
  `email_sender_email` VARCHAR(100) NULL DEFAULT NULL,
  `email_server_name` VARCHAR(50) NULL DEFAULT NULL,
  `email_port` VARCHAR(6) NULL DEFAULT NULL,
  `email_user_name` VARCHAR(100) NULL DEFAULT NULL,
  `email_password` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`email_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`request_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`request_status` (
  `rs_id` INT(11) NOT NULL,
  `rs_name` VARCHAR(50) NULL DEFAULT NULL,
  `rs_active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`rs_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`process_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`process_request` (
  `pr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pr_request_id` INT(11) NULL DEFAULT NULL,
  `pr_division_id` INT(11) NULL DEFAULT NULL,
  `pr_user_id` INT(11) NULL DEFAULT NULL,
  `pr_txn_date` DATETIME NULL DEFAULT NULL,
  `pr_status_id` INT(11) NULL DEFAULT NULL,
  `pr_note` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`pr_id`),
  INDEX `fk_pr_request_id_idx` (`pr_request_id` ASC),
  INDEX `fk_pr_status_id_idx` (`pr_status_id` ASC),
  CONSTRAINT `fk_pr_request_id`
    FOREIGN KEY (`pr_request_id`)
    REFERENCES `divsec`.`request` (`req_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pr_status_id`
    FOREIGN KEY (`pr_status_id`)
    REFERENCES `divsec`.`request_status` (`rs_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Request Processing details and the progress are updated.';


-- -----------------------------------------------------
-- Table `divsec`.`instructions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`instructions` (
  `ins_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ins_pr_id` INT(11) NULL DEFAULT NULL,
  `ins_instruction` VARCHAR(100) NULL DEFAULT NULL,
  `ins_date` DATETIME NULL DEFAULT NULL,
  `ins_is_read` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ins_id`),
  INDEX `fk_ins_pr_id_idx` (`ins_pr_id` ASC),
  CONSTRAINT `fk_ins_pr_id`
    FOREIGN KEY (`ins_pr_id`)
    REFERENCES `divsec`.`process_request` (`pr_request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`stage_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`stage_status` (
  `ss_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ss_name` VARCHAR(50) NULL DEFAULT NULL,
  `ss_active` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`ss_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`process_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`process_stage` (
  `rst_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rst_pr_id` INT(11) NOT NULL,
  `rst_stg_id` INT(11) NULL DEFAULT NULL,
  `rst_stage_status_id` INT(11) NOT NULL,
  `rs_sequence_no` INT(11) NULL DEFAULT NULL,
  `rst_txn_date` DATETIME NULL DEFAULT NULL,
  `rst_note` VARCHAR(100) NULL DEFAULT NULL,
  `rst_user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`rst_id`),
  INDEX `fk_rst_stage_status_idx` (`rst_stage_status_id` ASC),
  INDEX `fk_rst_user_id_idx` (`rst_user_id` ASC),
  INDEX `fk_stg_pr_id_idx` (`rst_pr_id` ASC),
  CONSTRAINT `fk_rst_pr_id`
    FOREIGN KEY (`rst_pr_id`)
    REFERENCES `divsec`.`process_request` (`pr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rst_stage_status`
    FOREIGN KEY (`rst_stage_status_id`)
    REFERENCES `divsec`.`stage_status` (`ss_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rst_user_id`
    FOREIGN KEY (`rst_user_id`)
    REFERENCES `divsec`.`staff` (`stf_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`request_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`request_log` (
  `rl_id` INT(11) NOT NULL AUTO_INCREMENT,
  `rl_pr_id` INT(11) NULL DEFAULT NULL,
  `rl_txn_date` DATETIME NULL DEFAULT NULL,
  `rl_division_id` INT(11) NULL DEFAULT NULL,
  `rl_status_id` INT(11) NULL DEFAULT NULL,
  `rl_user_id` INT(11) NULL DEFAULT NULL,
  `rl_note` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`rl_id`),
  INDEX `fk_req_id_idx` (`rl_pr_id` ASC),
  CONSTRAINT `fk_pr_id`
    FOREIGN KEY (`rl_pr_id`)
    REFERENCES `divsec`.`process_request` (`pr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`sms_setup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`sms_setup` (
  `sms_id` INT(11) NOT NULL,
  `sms_com_port_id` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`sms_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`stage_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`stage_log` (
  `ps_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ps_rst_id` INT(11) NULL DEFAULT NULL,
  `ps_stage_id` INT(11) NULL DEFAULT NULL,
  `ps_status_id` INT(11) NULL DEFAULT NULL,
  `ps_txn_date` DATETIME NULL DEFAULT NULL,
  `ps_user_id` INT(11) NULL DEFAULT NULL,
  `ps_note` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ps_id`),
  INDEX `fk_rst_id_idx` (`ps_rst_id` ASC),
  CONSTRAINT `fk_rst_id`
    FOREIGN KEY (`ps_rst_id`)
    REFERENCES `divsec`.`process_stage` (`rst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `divsec`.`subjec_stage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`subjec_stage` (
  `stg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `stg_subject_id` INT(11) NULL DEFAULT NULL,
  `stg_name` VARCHAR(100) NULL DEFAULT NULL,
  `stg_active` BIT(1) NULL DEFAULT NULL,
  `stg_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`stg_id`),
  INDEX `fk_sbject_id_idx` (`stg_subject_id` ASC),
  CONSTRAINT `fk_sbject_id`
    FOREIGN KEY (`stg_subject_id`)
    REFERENCES `divsec`.`subject` (`sbj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COMMENT = 'Stages for a subject that is to be completed.';

USE `divsec` ;

-- -----------------------------------------------------
-- Placeholder table for view `divsec`.`vw_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `divsec`.`vw_test` (`div_id` INT, `div_name` INT, `div_active` INT);

-- -----------------------------------------------------
-- View `divsec`.`vw_test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divsec`.`vw_test`;
USE `divsec`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `divsec`.`vw_test` AS select `divsec`.`division`.`div_id` AS `div_id`,`divsec`.`division`.`div_name` AS `div_name`,`divsec`.`division`.`div_active` AS `div_active` from `divsec`.`division`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
