// default package
// Generated Sep 30, 2015 10:10:01 PM by Hibernate Tools 4.3.1
package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Aproval generated by hbm2java
 */
@Entity
@Table(name = "aproval", catalog = "divsec")
public class Aproval implements java.io.Serializable {

	private Integer appId;
	private Request request;
	private Boolean appIsApproved;
	private Date appDate;
	private Date appEntDate;
	private Integer appUserId;

	public Aproval() {
	}

	public Aproval(Request request) {
		this.request = request;
	}

	public Aproval(Request request, Boolean appIsApproved, Date appDate, Date appEntDate, Integer appUserId) {
		this.request = request;
		this.appIsApproved = appIsApproved;
		this.appDate = appDate;
		this.appEntDate = appEntDate;
		this.appUserId = appUserId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_id", unique = true, nullable = false)
	public Integer getAppId() {
		return this.appId;
	}

	public void setAppId(Integer appId) {
		this.appId = appId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_request_id", nullable = false)
	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	@Column(name = "app_is_approved")
	public Boolean getAppIsApproved() {
		return this.appIsApproved;
	}

	public void setAppIsApproved(Boolean appIsApproved) {
		this.appIsApproved = appIsApproved;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "app_date", length = 19)
	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "app_ent_date", length = 19)
	public Date getAppEntDate() {
		return this.appEntDate;
	}

	public void setAppEntDate(Date appEntDate) {
		this.appEntDate = appEntDate;
	}

	@Column(name = "app_user_id")
	public Integer getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(Integer appUserId) {
		this.appUserId = appUserId;
	}

}
