package com.aymen.entity;
import java.util.Date;

/**
 * Aproval generated by hbm2java
 */
public class Aproval implements java.io.Serializable {

	private int appId;
	private Request request;
	private byte[] appIsApproved;
	private Date appDate;
	private Date appEntDate;
	private String appUserId;

	public Aproval() {
	}

	public Aproval(int appId, Request request) {
		this.appId = appId;
		this.request = request;
	}

	public Aproval(int appId, Request request, byte[] appIsApproved,
			Date appDate, Date appEntDate, String appUserId) {
		this.appId = appId;
		this.request = request;
		this.appIsApproved = appIsApproved;
		this.appDate = appDate;
		this.appEntDate = appEntDate;
		this.appUserId = appUserId;
	}

	public int getAppId() {
		return this.appId;
	}

	public void setAppId(int appId) {
		this.appId = appId;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public byte[] getAppIsApproved() {
		return this.appIsApproved;
	}

	public void setAppIsApproved(byte[] appIsApproved) {
		this.appIsApproved = appIsApproved;
	}

	public Date getAppDate() {
		return this.appDate;
	}

	public void setAppDate(Date appDate) {
		this.appDate = appDate;
	}

	public Date getAppEntDate() {
		return this.appEntDate;
	}

	public void setAppEntDate(Date appEntDate) {
		this.appEntDate = appEntDate;
	}

	public String getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(String appUserId) {
		this.appUserId = appUserId;
	}

}
