package com.aymen.entity;
// Generated May 5, 2016 7:28:20 AM by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientRole generated by hbm2java
 */
@Entity
@Table(name = "client_role", catalog = "divsec")
@JsonIdentityInfo(generator = ObjectIdGenerators.None.class, property = "@id")
public class ClientRole implements java.io.Serializable {

    private Integer id;
    private PublicIndividual publicIndividual;
    private Integer roleRoleId;
    private String roleRoleName;

    public ClientRole() {
    }

    public ClientRole(PublicIndividual publicIndividual) {
        this.publicIndividual = publicIndividual;
    }

    public ClientRole(PublicIndividual publicIndividual, Integer roleRoleId, String roleRoleName) {
        this.publicIndividual = publicIndividual;
        this.roleRoleId = roleRoleId;
        this.roleRoleName = roleRoleName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "role_client_id", nullable = false)
    public PublicIndividual getPublicIndividual() {
        return this.publicIndividual;
    }

    public void setPublicIndividual(PublicIndividual publicIndividual) {
        this.publicIndividual = publicIndividual;
    }

    @Column(name = "role_role_id")
    public Integer getRoleRoleId() {
        return this.roleRoleId;
    }

    public void setRoleRoleId(Integer roleRoleId) {
        this.roleRoleId = roleRoleId;
    }

    @Column(name = "role_role_name", length = 45)
    public String getRoleRoleName() {
        return this.roleRoleName;
    }

    public void setRoleRoleName(String roleRoleName) {
        this.roleRoleName = roleRoleName;
    }

}
