package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Division generated by hbm2java
 */
public class Division implements java.io.Serializable {

	private Integer divId;
	private String divName;
	private byte[] divActive;
	private Set requests = new HashSet(0);

	public Division() {
	}

	public Division(String divName, byte[] divActive, Set requests) {
		this.divName = divName;
		this.divActive = divActive;
		this.requests = requests;
	}

	public Integer getDivId() {
		return this.divId;
	}

	public void setDivId(Integer divId) {
		this.divId = divId;
	}

	public String getDivName() {
		return this.divName;
	}

	public void setDivName(String divName) {
		this.divName = divName;
	}

	public byte[] getDivActive() {
		return this.divActive;
	}

	public void setDivActive(byte[] divActive) {
		this.divActive = divActive;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

}
