package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

/**
 * EmailSetup generated by hbm2java
 */
public class EmailSetup implements java.io.Serializable {

	private Integer emailId;
	private byte[] emailIsOutLook;
	private String emailSenderName;
	private String emailSenderEmail;
	private String emailServerName;
	private String emailPort;
	private String emailUserName;
	private String emailPassword;

	public EmailSetup() {
	}

	public EmailSetup(byte[] emailIsOutLook, String emailSenderName,
			String emailSenderEmail, String emailServerName, String emailPort,
			String emailUserName, String emailPassword) {
		this.emailIsOutLook = emailIsOutLook;
		this.emailSenderName = emailSenderName;
		this.emailSenderEmail = emailSenderEmail;
		this.emailServerName = emailServerName;
		this.emailPort = emailPort;
		this.emailUserName = emailUserName;
		this.emailPassword = emailPassword;
	}

	public Integer getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Integer emailId) {
		this.emailId = emailId;
	}

	public byte[] getEmailIsOutLook() {
		return this.emailIsOutLook;
	}

	public void setEmailIsOutLook(byte[] emailIsOutLook) {
		this.emailIsOutLook = emailIsOutLook;
	}

	public String getEmailSenderName() {
		return this.emailSenderName;
	}

	public void setEmailSenderName(String emailSenderName) {
		this.emailSenderName = emailSenderName;
	}

	public String getEmailSenderEmail() {
		return this.emailSenderEmail;
	}

	public void setEmailSenderEmail(String emailSenderEmail) {
		this.emailSenderEmail = emailSenderEmail;
	}

	public String getEmailServerName() {
		return this.emailServerName;
	}

	public void setEmailServerName(String emailServerName) {
		this.emailServerName = emailServerName;
	}

	public String getEmailPort() {
		return this.emailPort;
	}

	public void setEmailPort(String emailPort) {
		this.emailPort = emailPort;
	}

	public String getEmailUserName() {
		return this.emailUserName;
	}

	public void setEmailUserName(String emailUserName) {
		this.emailUserName = emailUserName;
	}

	public String getEmailPassword() {
		return this.emailPassword;
	}

	public void setEmailPassword(String emailPassword) {
		this.emailPassword = emailPassword;
	}

}
