package com.aymen.entity;
// Generated May 9, 2016 8:04:27 PM by Hibernate Tools 4.3.1

import com.aymen.component.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Holiday generated by hbm2java
 */
@Entity
@Table(name = "holiday", catalog = "divsec", uniqueConstraints = @UniqueConstraint(columnNames = "hol_date")
)
public class Holiday implements java.io.Serializable {

    private Integer holId;
    private Date holDate;
    private String holDesc;
    private Boolean holIsActive;

    public Holiday() {
    }

    public Holiday(Date holDate, String holDesc, Boolean holIsActive) {
        this.holDate = holDate;
        this.holDesc = holDesc;
        this.holIsActive = holIsActive;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "hol_id", unique = true, nullable = false)
    public Integer getHolId() {
        return this.holId;
    }

    public void setHolId(Integer holId) {
        this.holId = holId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "hol_date", unique = true, length = 19)
    @JsonSerialize(using = JsonDateSerializer.class)
    public Date getHolDate() {
        return this.holDate;
    }

    public void setHolDate(Date holDate) {
        this.holDate = holDate;
    }

    @Column(name = "hol_desc", length = 50)
    public String getHolDesc() {
        return this.holDesc;
    }

    public void setHolDesc(String holDesc) {
        this.holDesc = holDesc;
    }

    @Column(name = "hol_is_active")
    public Boolean getHolIsActive() {
        return this.holIsActive;
    }

    public void setHolIsActive(Boolean holIsActive) {
        this.holIsActive = holIsActive;
    }

}
