package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Instructions generated by hbm2java
 */
public class Instructions implements java.io.Serializable {

	private Integer insId;
	private ProcessRequest processRequest;
	private String insInstruction;
	private Date insDate;
	private byte[] insIsRead;

	public Instructions() {
	}

	public Instructions(ProcessRequest processRequest, String insInstruction,
			Date insDate, byte[] insIsRead) {
		this.processRequest = processRequest;
		this.insInstruction = insInstruction;
		this.insDate = insDate;
		this.insIsRead = insIsRead;
	}

	public Integer getInsId() {
		return this.insId;
	}

	public void setInsId(Integer insId) {
		this.insId = insId;
	}

	public ProcessRequest getProcessRequest() {
		return this.processRequest;
	}

	public void setProcessRequest(ProcessRequest processRequest) {
		this.processRequest = processRequest;
	}

	public String getInsInstruction() {
		return this.insInstruction;
	}

	public void setInsInstruction(String insInstruction) {
		this.insInstruction = insInstruction;
	}

	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

	public byte[] getInsIsRead() {
		return this.insIsRead;
	}

	public void setInsIsRead(byte[] insIsRead) {
		this.insIsRead = insIsRead;
	}

}
