// default package
// Generated Sep 30, 2015 10:10:01 PM by Hibernate Tools 4.3.1
package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "divsec")
@JsonIdentityInfo(generator = ObjectIdGenerators.None.class, property = "@ntnId")
public class Notification implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer ntnId;
	private String ntnType;
	private Boolean ntnActive;
	private Set<PublicIndividual> publicIndividuals = new HashSet<PublicIndividual>(0);

	public Notification() {
	}

	public Notification(String ntnType, Boolean ntnActive, Set<PublicIndividual> publicIndividuals) {
		this.ntnType = ntnType;
		this.ntnActive = ntnActive;
		this.publicIndividuals = publicIndividuals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ntn_id", unique = true, nullable = false)
	public Integer getNtnId() {
		return this.ntnId;
	}

	public void setNtnId(Integer ntnId) {
		this.ntnId = ntnId;
	}

	@Column(name = "ntn_type", length = 100)
	public String getNtnType() {
		return this.ntnType;
	}

	public void setNtnType(String ntnType) {
		this.ntnType = ntnType;
	}

	@Column(name = "ntn_active")
	public Boolean getNtnActive() {
		return this.ntnActive;
	}

	public void setNtnActive(Boolean ntnActive) {
		this.ntnActive = ntnActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notification")
	@JsonIgnore
	public Set<PublicIndividual> getPublicIndividuals() {
		return this.publicIndividuals;
	}

	public void setPublicIndividuals(Set<PublicIndividual> publicIndividuals) {
		this.publicIndividuals = publicIndividuals;
	}

}
