package com.aymen.entity;
import java.util.HashSet;
import java.util.Set;

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	private int ntnId;
	private String ntnType;
	private byte[] ntnActive;
	private Set publicIndividuals = new HashSet(0);

	public Notification() {
	}

	public Notification(int ntnId) {
		this.ntnId = ntnId;
	}

	public Notification(int ntnId, String ntnType, byte[] ntnActive,
			Set publicIndividuals) {
		this.ntnId = ntnId;
		this.ntnType = ntnType;
		this.ntnActive = ntnActive;
		this.publicIndividuals = publicIndividuals;
	}

	public int getNtnId() {
		return this.ntnId;
	}

	public void setNtnId(int ntnId) {
		this.ntnId = ntnId;
	}

	public String getNtnType() {
		return this.ntnType;
	}

	public void setNtnType(String ntnType) {
		this.ntnType = ntnType;
	}

	public byte[] getNtnActive() {
		return this.ntnActive;
	}

	public void setNtnActive(byte[] ntnActive) {
		this.ntnActive = ntnActive;
	}

	public Set getPublicIndividuals() {
		return this.publicIndividuals;
	}

	public void setPublicIndividuals(Set publicIndividuals) {
		this.publicIndividuals = publicIndividuals;
	}

}
