package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessStage generated by hbm2java
 */
public class ProcessStage implements java.io.Serializable {

	private int rstId;
	private ProcessRequest processRequest;
	private Staff staff;
	private StageStatus stageStatus;
	private Integer rstStgId;
	private Integer rsSequenceNo;
	private Date rstTxnDate;
	private String rstNote;
	private Set stageLogs = new HashSet(0);

	public ProcessStage() {
	}

	public ProcessStage(int rstId, ProcessRequest processRequest,
			StageStatus stageStatus) {
		this.rstId = rstId;
		this.processRequest = processRequest;
		this.stageStatus = stageStatus;
	}

	public ProcessStage(int rstId, ProcessRequest processRequest, Staff staff,
			StageStatus stageStatus, Integer rstStgId, Integer rsSequenceNo,
			Date rstTxnDate, String rstNote, Set stageLogs) {
		this.rstId = rstId;
		this.processRequest = processRequest;
		this.staff = staff;
		this.stageStatus = stageStatus;
		this.rstStgId = rstStgId;
		this.rsSequenceNo = rsSequenceNo;
		this.rstTxnDate = rstTxnDate;
		this.rstNote = rstNote;
		this.stageLogs = stageLogs;
	}

	public int getRstId() {
		return this.rstId;
	}

	public void setRstId(int rstId) {
		this.rstId = rstId;
	}

	public ProcessRequest getProcessRequest() {
		return this.processRequest;
	}

	public void setProcessRequest(ProcessRequest processRequest) {
		this.processRequest = processRequest;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public StageStatus getStageStatus() {
		return this.stageStatus;
	}

	public void setStageStatus(StageStatus stageStatus) {
		this.stageStatus = stageStatus;
	}

	public Integer getRstStgId() {
		return this.rstStgId;
	}

	public void setRstStgId(Integer rstStgId) {
		this.rstStgId = rstStgId;
	}

	public Integer getRsSequenceNo() {
		return this.rsSequenceNo;
	}

	public void setRsSequenceNo(Integer rsSequenceNo) {
		this.rsSequenceNo = rsSequenceNo;
	}

	public Date getRstTxnDate() {
		return this.rstTxnDate;
	}

	public void setRstTxnDate(Date rstTxnDate) {
		this.rstTxnDate = rstTxnDate;
	}

	public String getRstNote() {
		return this.rstNote;
	}

	public void setRstNote(String rstNote) {
		this.rstNote = rstNote;
	}

	public Set getStageLogs() {
		return this.stageLogs;
	}

	public void setStageLogs(Set stageLogs) {
		this.stageLogs = stageLogs;
	}

}
