package com.aymen.entity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProcessRequest generated by hbm2java
 */
public class ProcessRequest implements java.io.Serializable {

	private Integer prId;
	private Request request;
	private RequestStatus requestStatus;
	private Integer prDivisionId;
	private Integer prUserId;
	private Date prTxnDate;
	private String prNote;
	private Set requestLogs = new HashSet(0);
	private Set instructionses = new HashSet(0);
	private Set processStages = new HashSet(0);

	public ProcessRequest() {
	}

	public ProcessRequest(Request request, RequestStatus requestStatus,
			Integer prDivisionId, Integer prUserId, Date prTxnDate,
			String prNote, Set requestLogs, Set instructionses,
			Set processStages) {
		this.request = request;
		this.requestStatus = requestStatus;
		this.prDivisionId = prDivisionId;
		this.prUserId = prUserId;
		this.prTxnDate = prTxnDate;
		this.prNote = prNote;
		this.requestLogs = requestLogs;
		this.instructionses = instructionses;
		this.processStages = processStages;
	}

	public Integer getPrId() {
		return this.prId;
	}

	public void setPrId(Integer prId) {
		this.prId = prId;
	}

	public Request getRequest() {
		return this.request;
	}

	public void setRequest(Request request) {
		this.request = request;
	}

	public RequestStatus getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(RequestStatus requestStatus) {
		this.requestStatus = requestStatus;
	}

	public Integer getPrDivisionId() {
		return this.prDivisionId;
	}

	public void setPrDivisionId(Integer prDivisionId) {
		this.prDivisionId = prDivisionId;
	}

	public Integer getPrUserId() {
		return this.prUserId;
	}

	public void setPrUserId(Integer prUserId) {
		this.prUserId = prUserId;
	}

	public Date getPrTxnDate() {
		return this.prTxnDate;
	}

	public void setPrTxnDate(Date prTxnDate) {
		this.prTxnDate = prTxnDate;
	}

	public String getPrNote() {
		return this.prNote;
	}

	public void setPrNote(String prNote) {
		this.prNote = prNote;
	}

	public Set getRequestLogs() {
		return this.requestLogs;
	}

	public void setRequestLogs(Set requestLogs) {
		this.requestLogs = requestLogs;
	}

	public Set getInstructionses() {
		return this.instructionses;
	}

	public void setInstructionses(Set instructionses) {
		this.instructionses = instructionses;
	}

	public Set getProcessStages() {
		return this.processStages;
	}

	public void setProcessStages(Set processStages) {
		this.processStages = processStages;
	}

}
