package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PublicIndividual generated by hbm2java
 */
public class PublicIndividual implements java.io.Serializable {

	private Integer piId;
	private Notification notification;
	private String piName;
	private String piAddress1;
	private String piAddress2;
	private String piAddress3;
	private String piLandPhone;
	private String piMobilePhone;
	private String piEmail;
	private Integer piIndUserId;
	private String piUserPwd;
	private String piNic;
	private Date piDob;
	private String piGender;
	private String piNote;
	private Integer piUserId;
	private Set requests = new HashSet(0);

	public PublicIndividual() {
	}

	public PublicIndividual(Notification notification, String piName,
			String piAddress1, String piAddress2, String piAddress3,
			String piLandPhone, String piMobilePhone, String piEmail,
			Integer piIndUserId, String piUserPwd, String piNic, Date piDob,
			String piGender, String piNote, Integer piUserId, Set requests) {
		this.notification = notification;
		this.piName = piName;
		this.piAddress1 = piAddress1;
		this.piAddress2 = piAddress2;
		this.piAddress3 = piAddress3;
		this.piLandPhone = piLandPhone;
		this.piMobilePhone = piMobilePhone;
		this.piEmail = piEmail;
		this.piIndUserId = piIndUserId;
		this.piUserPwd = piUserPwd;
		this.piNic = piNic;
		this.piDob = piDob;
		this.piGender = piGender;
		this.piNote = piNote;
		this.piUserId = piUserId;
		this.requests = requests;
	}

	public Integer getPiId() {
		return this.piId;
	}

	public void setPiId(Integer piId) {
		this.piId = piId;
	}

	public Notification getNotification() {
		return this.notification;
	}

	public void setNotification(Notification notification) {
		this.notification = notification;
	}

	public String getPiName() {
		return this.piName;
	}

	public void setPiName(String piName) {
		this.piName = piName;
	}

	public String getPiAddress1() {
		return this.piAddress1;
	}

	public void setPiAddress1(String piAddress1) {
		this.piAddress1 = piAddress1;
	}

	public String getPiAddress2() {
		return this.piAddress2;
	}

	public void setPiAddress2(String piAddress2) {
		this.piAddress2 = piAddress2;
	}

	public String getPiAddress3() {
		return this.piAddress3;
	}

	public void setPiAddress3(String piAddress3) {
		this.piAddress3 = piAddress3;
	}

	public String getPiLandPhone() {
		return this.piLandPhone;
	}

	public void setPiLandPhone(String piLandPhone) {
		this.piLandPhone = piLandPhone;
	}

	public String getPiMobilePhone() {
		return this.piMobilePhone;
	}

	public void setPiMobilePhone(String piMobilePhone) {
		this.piMobilePhone = piMobilePhone;
	}

	public String getPiEmail() {
		return this.piEmail;
	}

	public void setPiEmail(String piEmail) {
		this.piEmail = piEmail;
	}

	public Integer getPiIndUserId() {
		return this.piIndUserId;
	}

	public void setPiIndUserId(Integer piIndUserId) {
		this.piIndUserId = piIndUserId;
	}

	public String getPiUserPwd() {
		return this.piUserPwd;
	}

	public void setPiUserPwd(String piUserPwd) {
		this.piUserPwd = piUserPwd;
	}

	public String getPiNic() {
		return this.piNic;
	}

	public void setPiNic(String piNic) {
		this.piNic = piNic;
	}

	public Date getPiDob() {
		return this.piDob;
	}

	public void setPiDob(Date piDob) {
		this.piDob = piDob;
	}

	public String getPiGender() {
		return this.piGender;
	}

	public void setPiGender(String piGender) {
		this.piGender = piGender;
	}

	public String getPiNote() {
		return this.piNote;
	}

	public void setPiNote(String piNote) {
		this.piNote = piNote;
	}

	public Integer getPiUserId() {
		return this.piUserId;
	}

	public void setPiUserId(Integer piUserId) {
		this.piUserId = piUserId;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

}
