package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Request generated by hbm2java
 */
public class Request implements java.io.Serializable {

	private Integer reqId;
	private Division division;
	private PublicIndividual publicIndividual;
	private Staff staff;
	private Subject subject;
	private Date reqEntDate;
	private String reqNote;
	private BigDecimal reqFees;
	private byte[] reqToBeApproved;
	private Set aprovals = new HashSet(0);
	private Set processRequests = new HashSet(0);

	public Request() {
	}

	public Request(Division division, PublicIndividual publicIndividual,
			Staff staff, Subject subject, Date reqEntDate, String reqNote,
			BigDecimal reqFees, byte[] reqToBeApproved, Set aprovals,
			Set processRequests) {
		this.division = division;
		this.publicIndividual = publicIndividual;
		this.staff = staff;
		this.subject = subject;
		this.reqEntDate = reqEntDate;
		this.reqNote = reqNote;
		this.reqFees = reqFees;
		this.reqToBeApproved = reqToBeApproved;
		this.aprovals = aprovals;
		this.processRequests = processRequests;
	}

	public Integer getReqId() {
		return this.reqId;
	}

	public void setReqId(Integer reqId) {
		this.reqId = reqId;
	}

	public Division getDivision() {
		return this.division;
	}

	public void setDivision(Division division) {
		this.division = division;
	}

	public PublicIndividual getPublicIndividual() {
		return this.publicIndividual;
	}

	public void setPublicIndividual(PublicIndividual publicIndividual) {
		this.publicIndividual = publicIndividual;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Date getReqEntDate() {
		return this.reqEntDate;
	}

	public void setReqEntDate(Date reqEntDate) {
		this.reqEntDate = reqEntDate;
	}

	public String getReqNote() {
		return this.reqNote;
	}

	public void setReqNote(String reqNote) {
		this.reqNote = reqNote;
	}

	public BigDecimal getReqFees() {
		return this.reqFees;
	}

	public void setReqFees(BigDecimal reqFees) {
		this.reqFees = reqFees;
	}

	public byte[] getReqToBeApproved() {
		return this.reqToBeApproved;
	}

	public void setReqToBeApproved(byte[] reqToBeApproved) {
		this.reqToBeApproved = reqToBeApproved;
	}

	public Set getAprovals() {
		return this.aprovals;
	}

	public void setAprovals(Set aprovals) {
		this.aprovals = aprovals;
	}

	public Set getProcessRequests() {
		return this.processRequests;
	}

	public void setProcessRequests(Set processRequests) {
		this.processRequests = processRequests;
	}

}
