package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * RequestStatus generated by hbm2java
 */
public class RequestStatus implements java.io.Serializable {

	private int rsId;
	private String rsName;
	private byte[] rsActive;
	private Set processRequests = new HashSet(0);

	public RequestStatus() {
	}

	public RequestStatus(int rsId) {
		this.rsId = rsId;
	}

	public RequestStatus(int rsId, String rsName, byte[] rsActive,
			Set processRequests) {
		this.rsId = rsId;
		this.rsName = rsName;
		this.rsActive = rsActive;
		this.processRequests = processRequests;
	}

	public int getRsId() {
		return this.rsId;
	}

	public void setRsId(int rsId) {
		this.rsId = rsId;
	}

	public String getRsName() {
		return this.rsName;
	}

	public void setRsName(String rsName) {
		this.rsName = rsName;
	}

	public byte[] getRsActive() {
		return this.rsActive;
	}

	public void setRsActive(byte[] rsActive) {
		this.rsActive = rsActive;
	}

	public Set getProcessRequests() {
		return this.processRequests;
	}

	public void setProcessRequests(Set processRequests) {
		this.processRequests = processRequests;
	}

}
