// default package
// Generated Sep 1, 2015 10:25:55 AM by Hibernate Tools 4.3.1
package com.aymen.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RequestStatus generated by hbm2java
 */
@Entity
@Table(name = "request_status", catalog = "divsec")
public class RequestStatus implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int rsId;
	private String rsName;
	private byte[] rsActive;
	private Set<ProcessRequest> processRequests = new HashSet<ProcessRequest>(0);

	public RequestStatus() {
	}

	public RequestStatus(int rsId) {
		this.rsId = rsId;
	}

	public RequestStatus(int rsId, String rsName, byte[] rsActive, Set<ProcessRequest> processRequests) {
		this.rsId = rsId;
		this.rsName = rsName;
		this.rsActive = rsActive;
		this.processRequests = processRequests;
	}

	@Id

	@Column(name = "rs_id", unique = true, nullable = false)
	public int getRsId() {
		return this.rsId;
	}

	public void setRsId(int rsId) {
		this.rsId = rsId;
	}

	@Column(name = "rs_name", length = 50)
	public String getRsName() {
		return this.rsName;
	}

	public void setRsName(String rsName) {
		this.rsName = rsName;
	}

	@Column(name = "rs_active")
	public byte[] getRsActive() {
		return this.rsActive;
	}

	public void setRsActive(byte[] rsActive) {
		this.rsActive = rsActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestStatus")
	public Set<ProcessRequest> getProcessRequests() {
		return this.processRequests;
	}

	public void setProcessRequests(Set<ProcessRequest> processRequests) {
		this.processRequests = processRequests;
	}

}
