package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * RequestLog generated by hbm2java
 */
public class RequestLog implements java.io.Serializable {

	private int rlId;
	private ProcessRequest processRequest;
	private Date rlTxnDate;
	private Integer rlDivisionId;
	private Integer rlStatusId;
	private Integer rlUserId;
	private String rlNote;

	public RequestLog() {
	}

	public RequestLog(int rlId) {
		this.rlId = rlId;
	}

	public RequestLog(int rlId, ProcessRequest processRequest, Date rlTxnDate,
			Integer rlDivisionId, Integer rlStatusId, Integer rlUserId,
			String rlNote) {
		this.rlId = rlId;
		this.processRequest = processRequest;
		this.rlTxnDate = rlTxnDate;
		this.rlDivisionId = rlDivisionId;
		this.rlStatusId = rlStatusId;
		this.rlUserId = rlUserId;
		this.rlNote = rlNote;
	}

	public int getRlId() {
		return this.rlId;
	}

	public void setRlId(int rlId) {
		this.rlId = rlId;
	}

	public ProcessRequest getProcessRequest() {
		return this.processRequest;
	}

	public void setProcessRequest(ProcessRequest processRequest) {
		this.processRequest = processRequest;
	}

	public Date getRlTxnDate() {
		return this.rlTxnDate;
	}

	public void setRlTxnDate(Date rlTxnDate) {
		this.rlTxnDate = rlTxnDate;
	}

	public Integer getRlDivisionId() {
		return this.rlDivisionId;
	}

	public void setRlDivisionId(Integer rlDivisionId) {
		this.rlDivisionId = rlDivisionId;
	}

	public Integer getRlStatusId() {
		return this.rlStatusId;
	}

	public void setRlStatusId(Integer rlStatusId) {
		this.rlStatusId = rlStatusId;
	}

	public Integer getRlUserId() {
		return this.rlUserId;
	}

	public void setRlUserId(Integer rlUserId) {
		this.rlUserId = rlUserId;
	}

	public String getRlNote() {
		return this.rlNote;
	}

	public void setRlNote(String rlNote) {
		this.rlNote = rlNote;
	}

}
