package com.aymen.entity;



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmsLog generated by hbm2java
 */
@Entity
@Table(name="sms_log"
    ,catalog="divsec"
)
public class SmsLog  implements java.io.Serializable {


     private Integer smsId;
     private Date smsDate;
     private Integer smsReqId;
     private Integer smsUserId;
     private String smsResponse;
     private String smsStatus;
     private Double smsCharges;

    public SmsLog() {
    }

    public SmsLog(Date smsDate, Integer smsReqId, Integer smsUserId, String smsResponse, String smsStatus, Double smsCharges) {
       this.smsDate = smsDate;
       this.smsReqId = smsReqId;
       this.smsUserId = smsUserId;
       this.smsResponse = smsResponse;
       this.smsStatus = smsStatus;
       this.smsCharges = smsCharges;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sms_id", unique=true, nullable=false)
    public Integer getSmsId() {
        return this.smsId;
    }
    
    public void setSmsId(Integer smsId) {
        this.smsId = smsId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sms_date", length=19)
    public Date getSmsDate() {
        return this.smsDate;
    }
    
    public void setSmsDate(Date smsDate) {
        this.smsDate = smsDate;
    }

    
    @Column(name="sms_req_id")
    public Integer getSmsReqId() {
        return this.smsReqId;
    }
    
    public void setSmsReqId(Integer smsReqId) {
        this.smsReqId = smsReqId;
    }

    
    @Column(name="sms_user_id")
    public Integer getSmsUserId() {
        return this.smsUserId;
    }
    
    public void setSmsUserId(Integer smsUserId) {
        this.smsUserId = smsUserId;
    }

    
    @Column(name="sms_response", length=100)
    public String getSmsResponse() {
        return this.smsResponse;
    }
    
    public void setSmsResponse(String smsResponse) {
        this.smsResponse = smsResponse;
    }

    
    @Column(name="sms_status", length=45)
    public String getSmsStatus() {
        return this.smsStatus;
    }
    
    public void setSmsStatus(String smsStatus) {
        this.smsStatus = smsStatus;
    }

    
    @Column(name="sms_charges", precision=4)
    public Double getSmsCharges() {
        return this.smsCharges;
    }
    
    public void setSmsCharges(Double smsCharges) {
        this.smsCharges = smsCharges;
    }




}


