package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

/**
 * SmsSetup generated by hbm2java
 */
public class SmsSetup implements java.io.Serializable {

	private int smsId;
	private String smsComPortId;

	public SmsSetup() {
	}

	public SmsSetup(int smsId) {
		this.smsId = smsId;
	}

	public SmsSetup(int smsId, String smsComPortId) {
		this.smsId = smsId;
		this.smsComPortId = smsComPortId;
	}

	public int getSmsId() {
		return this.smsId;
	}

	public void setSmsId(int smsId) {
		this.smsId = smsId;
	}

	public String getSmsComPortId() {
		return this.smsComPortId;
	}

	public void setSmsComPortId(String smsComPortId) {
		this.smsComPortId = smsComPortId;
	}

}
