// default package
// Generated Sep 1, 2015 10:25:55 AM by Hibernate Tools 4.3.1
package com.aymen.entity;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SmsSetup generated by hbm2java
 */
@Entity
@Table(name = "sms_setup", catalog = "divsec")
public class SmsSetup implements java.io.Serializable {

	private int smsId;
	private String smsComPortId;

	public SmsSetup() {
	}

	public SmsSetup(int smsId) {
		this.smsId = smsId;
	}

	public SmsSetup(int smsId, String smsComPortId) {
		this.smsId = smsId;
		this.smsComPortId = smsComPortId;
	}

	@Id

	@Column(name = "sms_id", unique = true, nullable = false)
	public int getSmsId() {
		return this.smsId;
	}

	public void setSmsId(int smsId) {
		this.smsId = smsId;
	}

	@Column(name = "sms_com_port_id", length = 45)
	public String getSmsComPortId() {
		return this.smsComPortId;
	}

	public void setSmsComPortId(String smsComPortId) {
		this.smsComPortId = smsComPortId;
	}

}
