package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Staff generated by hbm2java
 */
public class Staff implements java.io.Serializable {

	private int stfId;
	private UserCategory userCategory;
	private String stfName;
	private String stfUserId;
	private String stfPassword;
	private Integer stfDvisionId;
	private String stfEmail;
	private String stfMobile;
	private String stfNote;
	private byte[] stfActive;
	private Set processStages = new HashSet(0);
	private Set requests = new HashSet(0);

	public Staff() {
	}

	public Staff(int stfId) {
		this.stfId = stfId;
	}

	public Staff(int stfId, UserCategory userCategory, String stfName,
			String stfUserId, String stfPassword, Integer stfDvisionId,
			String stfEmail, String stfMobile, String stfNote,
			byte[] stfActive, Set processStages, Set requests) {
		this.stfId = stfId;
		this.userCategory = userCategory;
		this.stfName = stfName;
		this.stfUserId = stfUserId;
		this.stfPassword = stfPassword;
		this.stfDvisionId = stfDvisionId;
		this.stfEmail = stfEmail;
		this.stfMobile = stfMobile;
		this.stfNote = stfNote;
		this.stfActive = stfActive;
		this.processStages = processStages;
		this.requests = requests;
	}

	public int getStfId() {
		return this.stfId;
	}

	public void setStfId(int stfId) {
		this.stfId = stfId;
	}

	public UserCategory getUserCategory() {
		return this.userCategory;
	}

	public void setUserCategory(UserCategory userCategory) {
		this.userCategory = userCategory;
	}

	public String getStfName() {
		return this.stfName;
	}

	public void setStfName(String stfName) {
		this.stfName = stfName;
	}

	public String getStfUserId() {
		return this.stfUserId;
	}

	public void setStfUserId(String stfUserId) {
		this.stfUserId = stfUserId;
	}

	public String getStfPassword() {
		return this.stfPassword;
	}

	public void setStfPassword(String stfPassword) {
		this.stfPassword = stfPassword;
	}

	public Integer getStfDvisionId() {
		return this.stfDvisionId;
	}

	public void setStfDvisionId(Integer stfDvisionId) {
		this.stfDvisionId = stfDvisionId;
	}

	public String getStfEmail() {
		return this.stfEmail;
	}

	public void setStfEmail(String stfEmail) {
		this.stfEmail = stfEmail;
	}

	public String getStfMobile() {
		return this.stfMobile;
	}

	public void setStfMobile(String stfMobile) {
		this.stfMobile = stfMobile;
	}

	public String getStfNote() {
		return this.stfNote;
	}

	public void setStfNote(String stfNote) {
		this.stfNote = stfNote;
	}

	public byte[] getStfActive() {
		return this.stfActive;
	}

	public void setStfActive(byte[] stfActive) {
		this.stfActive = stfActive;
	}

	public Set getProcessStages() {
		return this.processStages;
	}

	public void setProcessStages(Set processStages) {
		this.processStages = processStages;
	}

	public Set getRequests() {
		return this.requests;
	}

	public void setRequests(Set requests) {
		this.requests = requests;
	}

}
