package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * StageStatus generated by hbm2java
 */
public class StageStatus implements java.io.Serializable {

	private Integer ssId;
	private String ssName;
	private byte[] ssActive;
	private Set processStages = new HashSet(0);

	public StageStatus() {
	}

	public StageStatus(String ssName, byte[] ssActive, Set processStages) {
		this.ssName = ssName;
		this.ssActive = ssActive;
		this.processStages = processStages;
	}

	public Integer getSsId() {
		return this.ssId;
	}

	public void setSsId(Integer ssId) {
		this.ssId = ssId;
	}

	public String getSsName() {
		return this.ssName;
	}

	public void setSsName(String ssName) {
		this.ssName = ssName;
	}

	public byte[] getSsActive() {
		return this.ssActive;
	}

	public void setSsActive(byte[] ssActive) {
		this.ssActive = ssActive;
	}

	public Set getProcessStages() {
		return this.processStages;
	}

	public void setProcessStages(Set processStages) {
		this.processStages = processStages;
	}

}
