package com.aymen.entity;
import java.util.Date;

/**
 * StageLog generated by hbm2java
 */
public class StageLog implements java.io.Serializable {

	private Integer psId;
	private ProcessStage processStage;
	private Integer psStageId;
	private Integer psStatusId;
	private Date psTxnDate;
	private Integer psUserId;
	private String psNote;

	public StageLog() {
	}

	public StageLog(ProcessStage processStage, Integer psStageId,
			Integer psStatusId, Date psTxnDate, Integer psUserId, String psNote) {
		this.processStage = processStage;
		this.psStageId = psStageId;
		this.psStatusId = psStatusId;
		this.psTxnDate = psTxnDate;
		this.psUserId = psUserId;
		this.psNote = psNote;
	}

	public Integer getPsId() {
		return this.psId;
	}

	public void setPsId(Integer psId) {
		this.psId = psId;
	}

	public ProcessStage getProcessStage() {
		return this.processStage;
	}

	public void setProcessStage(ProcessStage processStage) {
		this.processStage = processStage;
	}

	public Integer getPsStageId() {
		return this.psStageId;
	}

	public void setPsStageId(Integer psStageId) {
		this.psStageId = psStageId;
	}

	public Integer getPsStatusId() {
		return this.psStatusId;
	}

	public void setPsStatusId(Integer psStatusId) {
		this.psStatusId = psStatusId;
	}

	public Date getPsTxnDate() {
		return this.psTxnDate;
	}

	public void setPsTxnDate(Date psTxnDate) {
		this.psTxnDate = psTxnDate;
	}

	public Integer getPsUserId() {
		return this.psUserId;
	}

	public void setPsUserId(Integer psUserId) {
		this.psUserId = psUserId;
	}

	public String getPsNote() {
		return this.psNote;
	}

	public void setPsNote(String psNote) {
		this.psNote = psNote;
	}

}
