package com.aymen.entity;// default package
// Generated Aug 27, 2015 6:12:34 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subject generated by hbm2java
 */
@Entity
@Table(name = "subject", catalog = "divsec")
public class Subject implements java.io.Serializable {

	private Integer sbjId;
	private String sbjName;
	private byte[] sbjActive;
	private Set<SubjecStage> subjecStages = new HashSet<SubjecStage>(0);
	private Set<Request> requests = new HashSet<Request>(0);

	public Subject() {
	}

	public Subject(String sbjName, byte[] sbjActive,
			Set<SubjecStage> subjecStages, Set<Request> requests) {
		this.sbjName = sbjName;
		this.sbjActive = sbjActive;
		this.subjecStages = subjecStages;
		this.requests = requests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sbj_id", unique = true, nullable = false)
	public Integer getSbjId() {
		return this.sbjId;
	}

	public void setSbjId(Integer sbjId) {
		this.sbjId = sbjId;
	}

	@Column(name = "sbj_name", length = 50)
	public String getSbjName() {
		return this.sbjName;
	}

	public void setSbjName(String sbjName) {
		this.sbjName = sbjName;
	}

	@Column(name = "sbj_active")
	public byte[] getSbjActive() {
		return this.sbjActive;
	}

	public void setSbjActive(byte[] sbjActive) {
		this.sbjActive = sbjActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<SubjecStage> getSubjecStages() {
		return this.subjecStages;
	}

	public void setSubjecStages(Set<SubjecStage> subjecStages) {
		this.subjecStages = subjecStages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subject")
	public Set<Request> getRequests() {
		return this.requests;
	}

	public void setRequests(Set<Request> requests) {
		this.requests = requests;
	}

}
