package com.aymen.entity;
// Generated Aug 24, 2015 8:39:18 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * SubjecStage generated by hbm2java
 */
public class SubjecStage implements java.io.Serializable {

	private Integer stgId;
	private Subject subject;
	private String stgName;
	private byte[] stgActive;
	private BigDecimal stgCost;

	public SubjecStage() {
	}

	public SubjecStage(Subject subject, String stgName, byte[] stgActive,
			BigDecimal stgCost) {
		this.subject = subject;
		this.stgName = stgName;
		this.stgActive = stgActive;
		this.stgCost = stgCost;
	}

	public Integer getStgId() {
		return this.stgId;
	}

	public void setStgId(Integer stgId) {
		this.stgId = stgId;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getStgName() {
		return this.stgName;
	}

	public void setStgName(String stgName) {
		this.stgName = stgName;
	}

	public byte[] getStgActive() {
		return this.stgActive;
	}

	public void setStgActive(byte[] stgActive) {
		this.stgActive = stgActive;
	}

	public BigDecimal getStgCost() {
		return this.stgCost;
	}

	public void setStgCost(BigDecimal stgCost) {
		this.stgCost = stgCost;
	}

}
