package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TicketPriority generated by hbm2java
 */
@Entity
@Table(name = "ticket_priority", catalog = "divsec")
public class TicketPriority implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String tktPriority;
	private Set<Ticket> tickets = new HashSet<Ticket>(0);

	public TicketPriority() {
	}

	public TicketPriority(String tktPriority, Set<Ticket> tickets) {
		this.tktPriority = tktPriority;
		this.tickets = tickets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tkt_priority", length = 20)
	public String getTktPriority() {
		return this.tktPriority;
	}

	public void setTktPriority(String tktPriority) {
		this.tktPriority = tktPriority;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketPriority")
	public Set<Ticket> getTickets() {
		return this.tickets;
	}

	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}

}
