package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "divsec")
public class Ticket implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer tktId;
	private Staff staffByTktFrom;
	private Staff staffByTktTo;
	private TicketPriority ticketPriority;
	private TicketStatus ticketStatus;
	private Integer tktReplyId;
	private Integer tktReplySequence;
	private Date tktDate;
	private String tktMessage;

	public Ticket() {
	}

	public Ticket(Staff staffByTktFrom, Staff staffByTktTo, TicketPriority ticketPriority, TicketStatus ticketStatus,
			Integer tktReplyId, Integer tktReplySequence, Date tktDate, String tktMessage) {
		this.staffByTktFrom = staffByTktFrom;
		this.staffByTktTo = staffByTktTo;
		this.ticketPriority = ticketPriority;
		this.ticketStatus = ticketStatus;
		this.tktReplyId = tktReplyId;
		this.tktReplySequence = tktReplySequence;
		this.tktDate = tktDate;
		this.tktMessage = tktMessage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tkt_id", unique = true, nullable = false)
	public Integer getTktId() {
		return this.tktId;
	}

	public void setTktId(Integer tktId) {
		this.tktId = tktId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tkt_from")
	public Staff getStaffByTktFrom() {
		return this.staffByTktFrom;
	}

	public void setStaffByTktFrom(Staff staffByTktFrom) {
		this.staffByTktFrom = staffByTktFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tkt_to")
	public Staff getStaffByTktTo() {
		return this.staffByTktTo;
	}

	public void setStaffByTktTo(Staff staffByTktTo) {
		this.staffByTktTo = staffByTktTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tkt_priority")
	public TicketPriority getTicketPriority() {
		return this.ticketPriority;
	}

	public void setTicketPriority(TicketPriority ticketPriority) {
		this.ticketPriority = ticketPriority;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tkt_status")
	public TicketStatus getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(TicketStatus ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

	@Column(name = "tkt_reply_id")
	public Integer getTktReplyId() {
		return this.tktReplyId;
	}

	public void setTktReplyId(Integer tktReplyId) {
		this.tktReplyId = tktReplyId;
	}

	@Column(name = "tkt_reply_sequence")
	public Integer getTktReplySequence() {
		return this.tktReplySequence;
	}

	public void setTktReplySequence(Integer tktReplySequence) {
		this.tktReplySequence = tktReplySequence;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tkt_date", length = 19)
	public Date getTktDate() {
		return this.tktDate;
	}

	public void setTktDate(Date tktDate) {
		this.tktDate = tktDate;
	}

	@Column(name = "tkt_message", length = 500)
	public String getTktMessage() {
		return this.tktMessage;
	}

	public void setTktMessage(String tktMessage) {
		this.tktMessage = tktMessage;
	}

}
