package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserCategory generated by hbm2java
 */
@Entity
@Table(name = "user_category", catalog = "divsec")
public class UserCategory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer catId;
	private String catName;
	private Set<Staff> staffs = new HashSet<Staff>(0);

	public UserCategory() {
	}

	public UserCategory(String catName, Set<Staff> staffs) {
		this.catName = catName;
		this.staffs = staffs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cat_id", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "cat_name", length = 50)
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "staff_role", catalog = "divsec", joinColumns = {
			@JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "staff_id", nullable = false, updatable = false) })
	@JsonIgnore
	public Set<Staff> getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set<Staff> staffs) {
		this.staffs = staffs;
	}

}
