package com.aymen.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserCategory generated by hbm2java
 */
@Entity
@Table(name = "user_category", catalog = "divsec", uniqueConstraints = @UniqueConstraint(columnNames = "cat_name") )
public class UserCategory implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer catId;
	private Staff staff;
	private String catName;

	public UserCategory() {
	}

	public UserCategory(Staff staff, String catName) {
		this.staff = staff;
		this.catName = catName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cat_id", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cat_user_id")
	@JsonIgnore
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Column(name = "cat_name", unique = true, length = 50)
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

}
